### ISSUE TITLE
Get Sensor Readings, and Perform Error Checking and Correction [R-3] [R-24]

### ISSUE THREAD

**Issue by rbebb** [rbebb/LANWeather#1]
Get sensor readings from attached sensors, and perform error checking and correction.

**Comment by Zippoman924** [comment]
Link to part page: 
https://www.adafruit.com/product/3251?gclid=EAIaIQobChMI0K3Xk-LW5wIVg5OzCh0I1whwEAAYASAAEgLJXPD_BwE

**Comment by Zippoman924** [comment]
Broke down into smaller issues, closing this ticket as a result.
