### ISSUE TITLE
Send Sensor Driver Data Back to Weather Service

### ISSUE THREAD

**Issue by rbebb** [rbebb/LANWeather#12]
**Ticket/Issue repurposed for new issue**

Write code that can call/interact with the sensor driver that can send data back to the weather service/server.

**Comment by Zippoman924** [comment]
**Ticket/Issue repurposed for new issue**

Write code that can call/interact with the sensor driver that can send data back to the weather service/server.

**Comment by Zippoman924** [comment]
When using zmq to send the data back to the weather service use port 5675. It should look something like this. 

```socket.connect("tcp://lw.minifigone.com:5675")```
