### ISSUE TITLE
Draft UI Layout Plan

### ISSUE THREAD

**Issue by rbebb** [rbebb/LANWeather#3]
1) Decide what info should be included for the breakdown of forecast data and current weather data
2) Decide if the app should use a single activity, single activity with multiple fragments, or multiple activities, etc.

Doodle and/or use Adobe XD to create what the layout will look like for approval. State your reasoning for major design choices.

**Comment by Eli-Labell** [comment]
Proposed Solution: One page for the weather data, current and forecast, another for the settings page. The weather data can be shown in a custom Array Adapter to hold hourly/daily data in Card Views for each time period respectively and the Settings can be static buttons. The buttons can store their states in the preference files and the weather data can be stored in a Room SQLite Db.

**Comment by rbebb** [comment]
Layout created in Adobe XD and basic layout created for the android app.
